-- MySQL Script generated by MySQL Workbench
-- Sat Apr 17 10:43:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `area` VARCHAR(100) NOT NULL,
  `ano_formacao` VARCHAR(100) NOT NULL,
  `nusp` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nusp`));


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_empresta_Eletronico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno_empresta_Eletronico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_empresta_Eletronico` (
  `Aluno_nusp` INT NOT NULL,
  `Equipamento Eletronico_idEletronico` INT NOT NULL,
  PRIMARY KEY (`Aluno_nusp`, `Equipamento Eletronico_idEletronico`),
  INDEX `fk_Aluno_has_Equipamento Eletronico_Equipamento Eletronico1_idx` (`Equipamento Eletronico_idEletronico` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Equipamento Eletronico_Aluno1_idx` (`Aluno_nusp` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Equipamento Eletronico_Aluno1`
    FOREIGN KEY (`Aluno_nusp`)
    REFERENCES `mydb`.`Aluno` (`nusp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Equipamento Eletronico_Equipamento Eletronico1`
    FOREIGN KEY (`Equipamento Eletronico_idEletronico`)
    REFERENCES `mydb`.`Equipamento Eletronico` (`idEletronico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`aluno_empresta_livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluno_empresta_livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluno_empresta_livro` (
  `Aluno_nusp` INT NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  PRIMARY KEY (`Aluno_nusp`, `Livro_idLivro`),
  INDEX `fk_Aluno_has_Livro_Livro1_idx` (`Livro_idLivro` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Livro_Aluno1_idx` (`Aluno_nusp` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Livro_Aluno1`
    FOREIGN KEY (`Aluno_nusp`)
    REFERENCES `mydb`.`Aluno` (`nusp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Livro_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `mydb`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_has_Equipamento de Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno_has_Equipamento de Laboratorio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_has_Equipamento de Laboratorio` (
  `Aluno_nusp` INT NOT NULL,
  `Equipamento de Laboratorio_idEquipamento_lab` INT NOT NULL,
  PRIMARY KEY (`Aluno_nusp`, `Equipamento de Laboratorio_idEquipamento_lab`),
  INDEX `fk_Aluno_has_Equipamento de Laboratorio_Equipamento de Labo_idx` (`Equipamento de Laboratorio_idEquipamento_lab` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Equipamento de Laboratorio_Aluno1_idx` (`Aluno_nusp` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Equipamento de Laboratorio_Aluno1`
    FOREIGN KEY (`Aluno_nusp`)
    REFERENCES `mydb`.`Aluno` (`nusp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Equipamento de Laboratorio_Equipamento de Labora1`
    FOREIGN KEY (`Equipamento de Laboratorio_idEquipamento_lab`)
    REFERENCES `mydb`.`Equipamento de Laboratorio` (`idEquipamento_lab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Biblioteca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca` (
  `idBiblioteca` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `area` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idBiblioteca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca_has_Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Biblioteca_has_Funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca_has_Funcionario` (
  `Biblioteca_idBiblioteca` INT NOT NULL,
  `Funcionario_nusp` INT NOT NULL,
  PRIMARY KEY (`Biblioteca_idBiblioteca`, `Funcionario_nusp`),
  INDEX `fk_Biblioteca_has_Funcionario_Funcionario1_idx` (`Funcionario_nusp` ASC) VISIBLE,
  INDEX `fk_Biblioteca_has_Funcionario_Biblioteca1_idx` (`Biblioteca_idBiblioteca` ASC) VISIBLE,
  CONSTRAINT `fk_Biblioteca_has_Funcionario_Biblioteca1`
    FOREIGN KEY (`Biblioteca_idBiblioteca`)
    REFERENCES `mydb`.`Biblioteca` (`idBiblioteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biblioteca_has_Funcionario_Funcionario1`
    FOREIGN KEY (`Funcionario_nusp`)
    REFERENCES `mydb`.`Funcionario` (`nusp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamento de Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipamento de Laboratorio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento de Laboratorio` (
  `idEquipamento_lab` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `disponivel` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `Laboratorio_idLaboratorio` INT NOT NULL,
  PRIMARY KEY (`idEquipamento_lab`),
  INDEX `fk_Equipamento de Laboratorio_Laboratorio1_idx` (`Laboratorio_idLaboratorio` ASC) VISIBLE,
  CONSTRAINT `fk_Equipamento de Laboratorio_Laboratorio1`
    FOREIGN KEY (`Laboratorio_idLaboratorio`)
    REFERENCES `mydb`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamento Eletronico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipamento Eletronico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento Eletronico` (
  `idEletronico` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `disponivel` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `ano` INT NOT NULL,
  `ultima_manutencao` VARCHAR(100) NOT NULL,
  `Biblioteca_idBiblioteca` INT NOT NULL,
  `Laboratorio_idLaboratorio` INT NOT NULL,
  PRIMARY KEY (`idEletronico`),
  INDEX `fk_Equipamento Eletronico_Biblioteca1_idx` (`Biblioteca_idBiblioteca` ASC) VISIBLE,
  INDEX `fk_Equipamento Eletronico_Laboratorio1_idx` (`Laboratorio_idLaboratorio` ASC) VISIBLE,
  CONSTRAINT `fk_Equipamento Eletronico_Biblioteca1`
    FOREIGN KEY (`Biblioteca_idBiblioteca`)
    REFERENCES `mydb`.`Biblioteca` (`idBiblioteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipamento Eletronico_Laboratorio1`
    FOREIGN KEY (`Laboratorio_idLaboratorio`)
    REFERENCES `mydb`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `local_trabalho` VARCHAR(100) NOT NULL,
  `funcao` VARCHAR(100) NOT NULL,
  `nusp` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nusp`));


-- -----------------------------------------------------
-- Table `mydb`.`Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Laboratorio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Laboratorio` (
  `idLaboratorio` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `departamento` VARCHAR(100) NOT NULL,
  `responsavel` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idLaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laboratorio_has_Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Laboratorio_has_Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Laboratorio_has_Professor` (
  `Laboratorio_idLaboratorio` INT NOT NULL,
  `Professor_nusp` INT NOT NULL,
  PRIMARY KEY (`Laboratorio_idLaboratorio`, `Professor_nusp`),
  INDEX `fk_Laboratorio_has_Professor_Professor1_idx` (`Professor_nusp` ASC) VISIBLE,
  INDEX `fk_Laboratorio_has_Professor_Laboratorio1_idx` (`Laboratorio_idLaboratorio` ASC) VISIBLE,
  CONSTRAINT `fk_Laboratorio_has_Professor_Laboratorio1`
    FOREIGN KEY (`Laboratorio_idLaboratorio`)
    REFERENCES `mydb`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Laboratorio_has_Professor_Professor1`
    FOREIGN KEY (`Professor_nusp`)
    REFERENCES `mydb`.`Professor` (`nusp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `idLivro` INT NOT NULL,
  `disponivel` VARCHAR(100) NOT NULL,
  `Biblioteca_idBiblioteca` INT NOT NULL,
  `tipoLivro_idtipoLivro` INT NOT NULL,
  PRIMARY KEY (`idLivro`),
  INDEX `fk_Livro_Biblioteca1_idx` (`Biblioteca_idBiblioteca` ASC) VISIBLE,
  INDEX `fk_Livro_tipoLivro1_idx` (`tipoLivro_idtipoLivro` ASC) VISIBLE,
  CONSTRAINT `fk_Livro_Biblioteca1`
    FOREIGN KEY (`Biblioteca_idBiblioteca`)
    REFERENCES `mydb`.`Biblioteca` (`idBiblioteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_tipoLivro1`
    FOREIGN KEY (`tipoLivro_idtipoLivro`)
    REFERENCES `mydb`.`tipoLivro` (`idtipoLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `sala` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(100) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `area_conhecimeto` VARCHAR(100) NOT NULL,
  `nusp` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(100) NULL,
  PRIMARY KEY (`nusp`));


-- -----------------------------------------------------
-- Table `mydb`.`Professor_empresta_Equipamento de Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor_empresta_Equipamento de Laboratorio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor_empresta_Equipamento de Laboratorio` (
  `Professor_nusp` INT NOT NULL,
  `Equipamento de Laboratorio_idEquipamento_lab` INT NOT NULL,
  PRIMARY KEY (`Professor_nusp`, `Equipamento de Laboratorio_idEquipamento_lab`),
  INDEX `fk_Professor_has_Equipamento de Laboratorio_Equipamento de _idx` (`Equipamento de Laboratorio_idEquipamento_lab` ASC) VISIBLE,
  INDEX `fk_Professor_has_Equipamento de Laboratorio_Professor1_idx` (`Professor_nusp` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Equipamento de Laboratorio_Professor1`
    FOREIGN KEY (`Professor_nusp`)
    REFERENCES `mydb`.`Professor` (`nusp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Equipamento de Laboratorio_Equipamento de La1`
    FOREIGN KEY (`Equipamento de Laboratorio_idEquipamento_lab`)
    REFERENCES `mydb`.`Equipamento de Laboratorio` (`idEquipamento_lab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Professor_empresta_Equipamento Eletronico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor_empresta_Equipamento Eletronico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor_empresta_Equipamento Eletronico` (
  `Professor_nusp` INT NOT NULL,
  `Equipamento Eletronico_idEletronico` INT NOT NULL,
  PRIMARY KEY (`Professor_nusp`, `Equipamento Eletronico_idEletronico`),
  INDEX `fk_Professor_has_Equipamento Eletronico_Equipamento Eletron_idx` (`Equipamento Eletronico_idEletronico` ASC) VISIBLE,
  INDEX `fk_Professor_has_Equipamento Eletronico_Professor1_idx` (`Professor_nusp` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Equipamento Eletronico_Professor1`
    FOREIGN KEY (`Professor_nusp`)
    REFERENCES `mydb`.`Professor` (`nusp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Equipamento Eletronico_Equipamento Eletronico1`
    FOREIGN KEY (`Equipamento Eletronico_idEletronico`)
    REFERENCES `mydb`.`Equipamento Eletronico` (`idEletronico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Professor_empresta_Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor_empresta_Livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor_empresta_Livro` (
  `Professor_nusp` INT NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  PRIMARY KEY (`Professor_nusp`, `Livro_idLivro`),
  INDEX `fk_Professor_has_Livro_Livro1_idx` (`Livro_idLivro` ASC) VISIBLE,
  INDEX `fk_Professor_has_Livro_Professor1_idx` (`Professor_nusp` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Livro_Professor1`
    FOREIGN KEY (`Professor_nusp`)
    REFERENCES `mydb`.`Professor` (`nusp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Livro_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `mydb`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tipoLivro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoLivro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoLivro` (
  `idtipoLivro` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `edicao` VARCHAR(100) NOT NULL,
  `ano` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipoLivro`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
