-- MySQL Script generated by MySQL Workbench
-- Mon Apr 19 10:24:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `nusp` INT NOT NULL,
  `area` VARCHAR(45) NULL,
  `ano_ingresso` INT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`nusp`),
  INDEX `fk_Aluno_Cadastro1_idx` (`nusp` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_has_Aparato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno_has_Aparato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_has_Aparato` (
  `Aluno_nusp` INT NOT NULL,
  `Aparato_idAparato` INT NOT NULL,
  PRIMARY KEY (`Aluno_nusp`, `Aparato_idAparato`),
  INDEX `fk_Aluno_has_Aparato_Aparato1_idx` (`Aparato_idAparato` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Aparato_Aluno1_idx` (`Aluno_nusp` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Aparato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aparato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aparato` (
  `idAparato` INT NOT NULL,
  `disponivel` CHAR(1) NOT NULL,
  PRIMARY KEY (`idAparato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Biblioteca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca` (
  `idBiblioteca` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idBiblioteca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca_has_Aparato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Biblioteca_has_Aparato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca_has_Aparato` (
  `Biblioteca_idBiblioteca` INT NOT NULL,
  `Aparato_idAparato` INT NOT NULL,
  PRIMARY KEY (`Biblioteca_idBiblioteca`, `Aparato_idAparato`),
  INDEX `fk_Biblioteca_has_Aparato_Aparato1_idx` (`Aparato_idAparato` ASC) VISIBLE,
  INDEX `fk_Biblioteca_has_Aparato_Biblioteca1_idx` (`Biblioteca_idBiblioteca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cadastro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro` (
  `nusp` INT NOT NULL,
  `Senha` VARCHAR(20) NULL,
  PRIMARY KEY (`nusp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento` (
  `Aparato_idAparato` INT NOT NULL,
  `tipo EquipLab_idtipo EquipLab` INT NOT NULL,
  `fabricado_em` DATE NULL,
  `ultima_manutencao` DATE NULL,
  PRIMARY KEY (`Aparato_idAparato`),
  INDEX `fk_Equipamento de Laboratorio_tipo EquipLab1_idx` (`tipo EquipLab_idtipo EquipLab` ASC) VISIBLE,
  INDEX `fk_Equipamento de Laboratorio_Aparato1_idx` (`Aparato_idAparato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `nusp` INT NOT NULL,
  `funcao` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`nusp`),
  INDEX `fk_Funcionario_Cadastro1_idx` (`nusp` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario_has_Aparato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario_has_Aparato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario_has_Aparato` (
  `Funcionario_nusp` INT NOT NULL,
  `Aparato_idAparato` INT NOT NULL,
  PRIMARY KEY (`Funcionario_nusp`, `Aparato_idAparato`),
  INDEX `fk_Funcionario_has_Aparato_Aparato1_idx` (`Aparato_idAparato` ASC) VISIBLE,
  INDEX `fk_Funcionario_has_Aparato_Funcionario1_idx` (`Funcionario_nusp` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Laboratorio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Laboratorio` (
  `idLaboratorio` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `departamento` VARCHAR(5) NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idLaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laboratorio_has_Aparato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Laboratorio_has_Aparato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Laboratorio_has_Aparato` (
  `Laboratorio_idLaboratorio` INT NOT NULL,
  `Aparato_idAparato` INT NOT NULL,
  PRIMARY KEY (`Laboratorio_idLaboratorio`, `Aparato_idAparato`),
  INDEX `fk_Laboratorio_has_Aparato_Aparato1_idx` (`Aparato_idAparato` ASC) VISIBLE,
  INDEX `fk_Laboratorio_has_Aparato_Laboratorio1_idx` (`Laboratorio_idLaboratorio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `Aparato_idAparato` INT NOT NULL,
  `tipoLivro_idtipoLivro` INT NOT NULL,
  PRIMARY KEY (`Aparato_idAparato`),
  INDEX `fk_Livro_tipoLivro1_idx` (`tipoLivro_idtipoLivro` ASC) VISIBLE,
  INDEX `fk_Livro_Aparato1_idx` (`Aparato_idAparato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `nusp` INT NOT NULL,
  `sala` VARCHAR(10) NULL,
  `cargo` VARCHAR(45) NULL,
  `departamento` VARCHAR(5) NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`nusp`),
  INDEX `fk_Professor_Cadastro1_idx` (`nusp` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Professor_has_Aparato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor_has_Aparato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor_has_Aparato` (
  `Professor_nusp` INT NOT NULL,
  `Aparato_idAparato` INT NOT NULL,
  PRIMARY KEY (`Professor_nusp`, `Aparato_idAparato`),
  INDEX `fk_Professor_has_Aparato_Aparato1_idx` (`Aparato_idAparato` ASC) VISIBLE,
  INDEX `fk_Professor_has_Aparato_Professor1_idx` (`Professor_nusp` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Responsavel_Por`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Responsavel_Por` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Responsavel_Por` (
  `Professor_nusp` INT NOT NULL,
  `Laboratorio_idLaboratorio` INT NOT NULL,
  PRIMARY KEY (`Professor_nusp`, `Laboratorio_idLaboratorio`),
  INDEX `fk_Professor_has_Laboratorio_Laboratorio1_idx` (`Laboratorio_idLaboratorio` ASC) VISIBLE,
  INDEX `fk_Professor_has_Laboratorio_Professor1_idx` (`Professor_nusp` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`tipoEquipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoEquipamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoEquipamento` (
  `idtipo EquipLab` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo EquipLab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoLivro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoLivro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoLivro` (
  `idtipoLivro` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(100) NULL,
  `edicao` INT NULL,
  `ano_lancamento` INT NULL,
  PRIMARY KEY (`idtipoLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabalha_Em`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Trabalha_Em` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Trabalha_Em` (
  `Funcionario_nusp` INT NOT NULL,
  `Biblioteca_idBiblioteca` INT NOT NULL,
  PRIMARY KEY (`Funcionario_nusp`, `Biblioteca_idBiblioteca`),
  INDEX `fk_Funcionario_has_Biblioteca_Biblioteca1_idx` (`Biblioteca_idBiblioteca` ASC) VISIBLE,
  INDEX `fk_Funcionario_has_Biblioteca_Funcionario1_idx` (`Funcionario_nusp` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
